"""Corrected Foreign Key

Revision ID: f024e6520c3a
Revises: 79a51000a838
Create Date: 2022-05-19 08:41:21.287629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f024e6520c3a'
down_revision = '79a51000a838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_interests_student_id_fkey', 'student_interests', type_='foreignkey')
    op.create_foreign_key(None, 'student_interests', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_interests', type_='foreignkey')
    op.create_foreign_key('student_interests_student_id_fkey', 'student_interests', 'interests', ['student_id'], ['id'])
    # ### end Alembic commands ###
